name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            SERVICES=("account" "cart" "inventory" "order-status" "payment" "place-order" "product-review" "recommendation" "recommendation-generation" "search" "shipping")
            for SERVICE in "${SERVICES[@]}"
            do
              docker pull ${{ secrets.DOCKER_USERNAME }}/$SERVICE:latest
              docker stop $SERVICE || true
              docker rm $SERVICE || true
              docker run -d --name $SERVICE -p [PORT_MAPPING] ${{ secrets.DOCKER_USERNAME }}/$SERVICE:latest
            done
          EOF
